POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "phone": "+998931234321",
  "password": "password",
  "birthDate": "24/11/2000"
}

###
GET http://localhost:8080/api/v1/registration/confirm?sms=49455


###
GET http://localhost:8080/api/v1/registration/againSmsCode?userId=7

###
GET http://localhost:8080/api/v1/registration/confirm?sms=73835